name: Sync

on:
  schedule:
  - cron:  "0 * * * *"
permissions:
  contents: read
  pull-requests: write  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/ipxe/ipxe.git"
        source_branch: "master"
        destination_branch: "ipxe"
        github_token: ${{ secrets.GITHUB_TOKEN }}
